system:
  id_system: xact_graph


###############################################################################
host:
  localhost:
    hostname:        'localhost'
    acct_run:        'wtp'
    acct_provision:  'wtp'
    port_range:      '8090-9000'
    dirpath_log:     '/var/log/xact'
    dirpath_install: '/home/wtp/dev/xact/'
    dirpath_venv:    '/home/wtp/dev/venv/'    # /opt/xact
    log_level:       'TRACE'


###############################################################################
process:
  reader_process:
    host: localhost
  worker_process:
    host: localhost
  server_process:
    host: localhost


###############################################################################
node:

  # ---------------------------------------------------------------------------
  controller:
    process:        reader_process
    req_host_cfg:   default_configuration
    functionality:
      py_module:    xact.lib.util.simple_controller
    state_type:     py_dict
    config:
      frequency_hz: 10

  # ---------------------------------------------------------------------------
  fs_monitor:
    process:        reader_process
    req_host_cfg:   default_configuration
    functionality:
      py_module:    xact.lib.fs.monitor
    state_type:     py_dict
    config:
      dirpath_root:
        - /media/wtp/Data/dev/xact_lib/src/xact/app/
      pathincl:
        - !regex '^.*.cfg.yaml$'
      direxcl:
        - !regex '^\..*$'
        - !regex '^.*\.egg-info$'
        - !regex '^.pytest-cache$'
        - !regex '^\.cache$'
        - !regex '^\.git$'
        - !regex '^\.tox$'
        - !regex '^\.vagrant$'
        - !regex '^__pycache__$'
      batch_size:    50
      changes:       True
      static_files:  True
      repeat_static: False
      halt_after:    False

  # ---------------------------------------------------------------------------
  cfg_reader:
    process:        reader_process
    req_host_cfg:   default_configuration
    functionality:
      py_module:    xact.lib.cfg.reader
    state_type:     py_dict

  # ---------------------------------------------------------------------------
  svg_renderer:
    process:        worker_process
    req_host_cfg:   default_configuration
    functionality:
      py_module:    xact.lib.cfg.renderer
    state_type:     py_dict

  # ---------------------------------------------------------------------------
  page_generator:
    process:        worker_process
    req_host_cfg:   default_configuration
    functionality:
      py_module:    xact.app.xact_graph.cfg_graph_display
    state_type:     py_dict

  # ---------------------------------------------------------------------------
  htmx:
    process:        worker_process
    req_host_cfg:   default_configuration
    functionality:
      py_module:    xact.lib.ui.web.resource_from_file
    state_type:     py_dict
    config:
      id_resource:  htmx
      media_type:   text/javascript
      filepath:     /media/wtp/Data/dev/oss/htmx/src/htmx.js

  # ---------------------------------------------------------------------------
  resource_merge:
    process:        server_process
    req_host_cfg:   default_configuration
    functionality:
      py_module:    xact.lib.util.merge_list
    state_type:     py_dict

  # ---------------------------------------------------------------------------
  webserver:
    process:        server_process
    req_host_cfg:   default_configuration
    functionality:
      py_module:    xact.lib.web.server
    state_type:     py_dict
    config:
      host:         0.0.0.0
      port:         8080
      session_key:  7A8F&+ey789dfgh+32d233shja67s843g1
      debug:        False


###############################################################################
edge:
- owner: controller
  data:  py_dict
  src:   controller.outputs.clock
  dst:   fs_monitor.inputs.clock

- owner: fs_monitor
  data:  py_dict
  src:   fs_monitor.outputs.filepath
  dst:   cfg_reader.inputs.filepath

- owner: cfg_reader
  data:  py_dict
  src:   cfg_reader.outputs.cfg
  dst:   svg_renderer.inputs.cfg

- owner: svg_renderer
  data:  py_dict
  src:   svg_renderer.outputs.svg
  dst:   page_generator.inputs.svg

- owner: resource_merge
  data:  py_dict
  src:   page_generator.outputs.resources
  dst:   resource_merge.inputs.resources_00

- owner: resource_merge
  data:  py_dict
  src:   htmx.outputs.resources
  dst:   resource_merge.inputs.resources_02

- owner: resource_merge
  data:  py_dict
  src:   resource_merge.outputs.resources
  dst:   webserver.inputs.resources


###############################################################################
data:
  py_dict:  py_dict
  py_str:   py_str


###############################################################################
req_host_cfg:
  default_configuration:
    role:
      - default_role


###############################################################################
role:
  default_role:
    tasks:
      - name: Update apt-get repo and cache
        become:        yes
        become_user:   root
        become_method: sudo
        apt:
          update_cache:     yes
          force_apt_get:    yes
          cache_valid_time: 3600
